09/03/2018 18:57:05.0250	[raft_python_callback.py write_to_logger 66]  250 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:init_state_functions_handler, LINE:28
MESSAGE:start
-----------------------------

09/03/2018 18:57:05.0250	[raft_python_callback.py write_to_logger 66]  250 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:init_state_functions_handler, LINE:70
MESSAGE:end
-----------------------------

09/03/2018 18:57:05.0250	[raft_python_callback.py write_to_logger 66]  250 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:init_multicast_message, LINE:81
MESSAGE:init multicast socket
-----------------------------

09/03/2018 18:57:05.0252	[raft_python_callback.py write_to_logger 66]  252 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:init_multicast_message, LINE:88
MESSAGE:multicast was opened successfully
-----------------------------

09/03/2018 18:57:05.0252	[raft_python_callback.py write_to_logger 66]  252 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:init_raft_queue, LINE:13
MESSAGE:first time
-----------------------------

09/03/2018 18:57:05.0252	[raft_python_callback.py write_to_logger 66]  252 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:create_alarm_timer, LINE:44
MESSAGE:create new alarm timer
VARIABLES:  sharedRaftData.raft_state.current_state=0  timeout=3798 
-----------------------------

09/03/2018 18:57:05.0252	[raft_python_callback.py write_to_logger 66]  252 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:update_DB, LINE:16
MESSAGE:update DB
VARIABLES:  DB_flag=status  key=status 
-----------------------------

09/03/2018 18:57:05.0252	[raft_python_callback.py write_to_logger 66]  252 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:update_DB, LINE:17
MESSAGE:update DB
VARIABLES:  value=-3 
-----------------------------

09/03/2018 18:57:05.0254	[raft_python_callback.py write_to_logger 66]  254 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:init_raft, LINE:154
MESSAGE:init succeed
-----------------------------

09/03/2018 18:57:05.0254	[raft_python_callback.py write_to_logger 66]  254 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_raft, LINE:195
MESSAGE:start raft...
VARIABLES:  raft_ip=230.1.1.10 
-----------------------------

09/03/2018 18:57:05.0254	[raft_python_callback.py write_to_logger 66]  254 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_raft, LINE:197
MESSAGE:start raft...
VARIABLES:  raft_port=12345  server_id=2  members_num=2  leader_timeout=500 
-----------------------------

09/03/2018 18:57:05.0254	[raft_python_callback.py write_to_logger 66]  254 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_raft, LINE:202
MESSAGE:run raft...
-----------------------------

09/03/2018 18:57:05.0254	[raft_python_callback.py write_to_logger 66]  254 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:08.0253	[raft_python_callback.py write_to_logger 66]  253 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=0 
-----------------------------

09/03/2018 18:57:08.0253	[raft_python_callback.py write_to_logger 66]  253 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=0 
-----------------------------

09/03/2018 18:57:11.0253	[raft_python_callback.py write_to_logger 66]  253 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=0 
-----------------------------

09/03/2018 18:57:11.0253	[raft_python_callback.py write_to_logger 66]  253 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=0 
-----------------------------

09/03/2018 18:57:11.0253	[raft_python_callback.py write_to_logger 66]  253 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:update_DB, LINE:16
MESSAGE:update DB
VARIABLES:  DB_flag=status  key=term 
-----------------------------

09/03/2018 18:57:11.0253	[raft_python_callback.py write_to_logger 66]  253 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:update_DB, LINE:17
MESSAGE:update DB
VARIABLES:  value=0 
-----------------------------

09/03/2018 18:57:11.0255	[raft_python_callback.py write_to_logger 66]  255 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:update_DB, LINE:16
MESSAGE:update DB
VARIABLES:  DB_flag=status  key=status 
-----------------------------

09/03/2018 18:57:11.0255	[raft_python_callback.py write_to_logger 66]  255 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:update_DB, LINE:17
MESSAGE:update DB
VARIABLES:  value=-2 
-----------------------------

09/03/2018 18:57:11.0256	[raft_python_callback.py write_to_logger 66]  256 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:update_DB, LINE:16
MESSAGE:update DB
VARIABLES:  DB_flag=status  key=leader_id 
-----------------------------

09/03/2018 18:57:11.0256	[raft_python_callback.py write_to_logger 66]  256 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:update_DB, LINE:17
MESSAGE:update DB
VARIABLES:  value=0 
-----------------------------

09/03/2018 18:57:11.0258	[raft_python_callback.py write_to_logger 66]  258 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=8 
-----------------------------

09/03/2018 18:57:11.0259	[raft_python_callback.py write_to_logger 66]  259 root [DEBUG] 
FILE:./C/Code/follower_handlers.c, FUNCTION:follower_time_out_handler, LINE:254
MESSAGE:follower became candidate and is sending request for vote msg
-----------------------------

09/03/2018 18:57:11.0259	[raft_python_callback.py write_to_logger 66]  259 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=20 
-----------------------------

09/03/2018 18:57:11.0259	[raft_python_callback.py write_to_logger 66]  259 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=20 
-----------------------------

09/03/2018 18:57:11.0259	[raft_python_callback.py write_to_logger 66]  259 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:init_raft_queue, LINE:23
MESSAGE:not first time
-----------------------------

09/03/2018 18:57:11.0260	[raft_python_callback.py write_to_logger 66]  260 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=20 
-----------------------------

09/03/2018 18:57:11.0260	[raft_python_callback.py write_to_logger 66]  260 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:11.0260	[raft_python_callback.py write_to_logger 66]  260 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:11.0411	[raft_python_callback.py write_to_logger 66]  411 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=20 
-----------------------------

09/03/2018 18:57:11.0411	[raft_python_callback.py write_to_logger 66]  411 root [INFO ] 
FILE:./C/Code/handlers_utils.c, FUNCTION:check_if_my_message, LINE:118
MESSAGE:This is my msg- ignore!
-----------------------------

09/03/2018 18:57:11.0411	[raft_python_callback.py write_to_logger 66]  411 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:is_relevant_for_candidate, LINE:92
MESSAGE:candidate check if msg is relevant
VARIABLES:  sharedRaftData.raft_state.term=0  sharedRaftData.raft_state.server_id=2  node_message->message_sent_to=2  node_message->term=0  node_message->event=7 
-----------------------------

09/03/2018 18:57:11.0411	[raft_python_callback.py write_to_logger 66]  411 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:is_relevant_for_candidate, LINE:106
MESSAGE:candidate:relevant msg
-----------------------------

09/03/2018 18:57:11.0411	[raft_python_callback.py write_to_logger 66]  411 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:is_relevant_message, LINE:168
MESSAGE:check if msg is relevant
VARIABLES:  sharedRaftData.raft_state.current_state=1  node_message->event=7  is_relevant_rv=1  node_message->term=0 
-----------------------------

09/03/2018 18:57:11.0411	[raft_python_callback.py write_to_logger 66]  411 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=1  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:11.0411	[raft_python_callback.py write_to_logger 66]  411 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:11.0412	[raft_python_callback.py write_to_logger 66]  412 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=7  sharedRaftData.raft_state.current_state=1 
-----------------------------

09/03/2018 18:57:11.0412	[raft_python_callback.py write_to_logger 66]  412 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:init_raft_queue, LINE:23
MESSAGE:not first time
-----------------------------

09/03/2018 18:57:11.0412	[raft_python_callback.py write_to_logger 66]  412 root [DEBUG] 
FILE:./C/Code/candidate_handlers.c, FUNCTION:candidate_vote_for_me_handler, LINE:20
MESSAGE:candidate got majority- becoming leader
VARIABLES:  node->event=7 
	 sharedRaftData.raft_state.term=0 
	 sharedRaftData.raft_state.current_state=2 
	 sharedRaftData.raft_state.vote_counter=2 
	 node->message_sent_by=1 
	 node->term=0 
	
-----------------------------

09/03/2018 18:57:11.0412	[raft_python_callback.py write_to_logger 66]  412 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:create_alarm_timer, LINE:44
MESSAGE:create new alarm timer
VARIABLES:  sharedRaftData.raft_state.current_state=2  timeout=500 
-----------------------------

09/03/2018 18:57:11.0412	[raft_python_callback.py write_to_logger 66]  412 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:update_DB, LINE:16
MESSAGE:update DB
VARIABLES:  DB_flag=status  key=status 
-----------------------------

09/03/2018 18:57:11.0412	[raft_python_callback.py write_to_logger 66]  412 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:update_DB, LINE:17
MESSAGE:update DB
VARIABLES:  value=-1 
-----------------------------

09/03/2018 18:57:11.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:update_DB, LINE:16
MESSAGE:update DB
VARIABLES:  DB_flag=status  key=leader_id 
-----------------------------

09/03/2018 18:57:11.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:update_DB, LINE:17
MESSAGE:update DB
VARIABLES:  value=2 
-----------------------------

09/03/2018 18:57:11.0415	[raft_python_callback.py write_to_logger 66]  415 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:11.0415	[raft_python_callback.py write_to_logger 66]  415 root [DEBUG] 
FILE:./C/Code/candidate_handlers.c, FUNCTION:candidate_vote_for_me_handler, LINE:40
MESSAGE:candidate sending keep alive hb msg
-----------------------------

09/03/2018 18:57:11.0415	[raft_python_callback.py write_to_logger 66]  415 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:11.0415	[raft_python_callback.py write_to_logger 66]  415 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:11.0416	[raft_python_callback.py write_to_logger 66]  416 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:11.0416	[raft_python_callback.py write_to_logger 66]  416 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:11.0416	[raft_python_callback.py write_to_logger 66]  416 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:11.0416	[raft_python_callback.py write_to_logger 66]  416 root [DEBUG] 
FILE:./C/Code/candidate_handlers.c, FUNCTION:candidate_vote_for_me_handler, LINE:64
MESSAGE:end of vote event
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:11.0912	[raft_python_callback.py write_to_logger 66]  912 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:11.0912	[raft_python_callback.py write_to_logger 66]  912 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:11.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:11.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:11.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:11.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:11.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:11.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:11.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:11.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:12.0412	[raft_python_callback.py write_to_logger 66]  412 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:12.0412	[raft_python_callback.py write_to_logger 66]  412 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:12.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:12.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:12.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:12.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:12.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:12.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:12.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:12.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:12.0912	[raft_python_callback.py write_to_logger 66]  912 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:12.0912	[raft_python_callback.py write_to_logger 66]  912 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:12.0912	[raft_python_callback.py write_to_logger 66]  912 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:12.0912	[raft_python_callback.py write_to_logger 66]  912 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:12.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:12.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:12.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:12.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:12.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:12.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:13.0412	[raft_python_callback.py write_to_logger 66]  412 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:13.0412	[raft_python_callback.py write_to_logger 66]  412 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:13.0412	[raft_python_callback.py write_to_logger 66]  412 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:13.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:13.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:13.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:13.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:13.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:13.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:13.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:13.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:13.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:13.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:13.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:13.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:13.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:13.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:13.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:13.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:13.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:14.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:14.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:14.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:14.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:14.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:14.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:14.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:14.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:14.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:14.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:14.0912	[raft_python_callback.py write_to_logger 66]  912 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:14.0912	[raft_python_callback.py write_to_logger 66]  912 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:14.0912	[raft_python_callback.py write_to_logger 66]  912 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:14.0912	[raft_python_callback.py write_to_logger 66]  912 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:14.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:14.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:14.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:14.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:14.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:14.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:15.0412	[raft_python_callback.py write_to_logger 66]  412 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:15.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:15.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:15.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:15.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:15.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:15.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:15.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:15.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:15.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:15.0915	[raft_python_callback.py write_to_logger 66]  915 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:15.0915	[raft_python_callback.py write_to_logger 66]  915 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:15.0915	[raft_python_callback.py write_to_logger 66]  915 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:15.0915	[raft_python_callback.py write_to_logger 66]  915 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:15.0916	[raft_python_callback.py write_to_logger 66]  916 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:15.0916	[raft_python_callback.py write_to_logger 66]  916 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:15.0916	[raft_python_callback.py write_to_logger 66]  916 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:15.0916	[raft_python_callback.py write_to_logger 66]  916 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:15.0916	[raft_python_callback.py write_to_logger 66]  916 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:15.0916	[raft_python_callback.py write_to_logger 66]  916 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:16.0412	[raft_python_callback.py write_to_logger 66]  412 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:16.0412	[raft_python_callback.py write_to_logger 66]  412 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:16.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:16.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:16.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:16.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:16.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:16.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:16.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:16.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:16.0912	[raft_python_callback.py write_to_logger 66]  912 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:16.0912	[raft_python_callback.py write_to_logger 66]  912 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:16.0912	[raft_python_callback.py write_to_logger 66]  912 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:16.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:16.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:16.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:16.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:16.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:16.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:16.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:17.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:17.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:17.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:17.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:17.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:17.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:17.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:17.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:17.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:17.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:17.0912	[raft_python_callback.py write_to_logger 66]  912 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:17.0912	[raft_python_callback.py write_to_logger 66]  912 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:17.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:17.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:17.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:17.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:17.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:17.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:17.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:17.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:18.0412	[raft_python_callback.py write_to_logger 66]  412 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:18.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:18.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:18.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:18.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:18.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:18.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:18.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:18.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:18.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:18.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:18.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:18.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:18.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:18.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:18.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:18.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:18.0915	[raft_python_callback.py write_to_logger 66]  915 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:18.0915	[raft_python_callback.py write_to_logger 66]  915 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:18.0915	[raft_python_callback.py write_to_logger 66]  915 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:19.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:19.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:19.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:19.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:19.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:19.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:19.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:19.0415	[raft_python_callback.py write_to_logger 66]  415 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:19.0415	[raft_python_callback.py write_to_logger 66]  415 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:19.0415	[raft_python_callback.py write_to_logger 66]  415 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:19.0912	[raft_python_callback.py write_to_logger 66]  912 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:19.0912	[raft_python_callback.py write_to_logger 66]  912 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:19.0912	[raft_python_callback.py write_to_logger 66]  912 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:19.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:19.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:19.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:19.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:19.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:19.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:19.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:20.0185	[raft_python_callback.py write_to_logger 66]  185 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:start_commit_process, LINE:173
MESSAGE: start commit process
-----------------------------

09/03/2018 18:57:20.0186	[raft_python_callback.py write_to_logger 66]  186 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=9  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:20.0186	[raft_python_callback.py write_to_logger 66]  186 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_send_log_hb_handler, LINE:180
MESSAGE:leader send new log entry
VARIABLES:  sharedRaftData.raft_state.last_commit_index=-1  sharedRaftData.raft_state.last_log_index=-1  sharedRaftData.raft_state.commit_counter=0  new_log_commit_id=0 
-----------------------------

09/03/2018 18:57:20.0186	[raft_python_callback.py write_to_logger 66]  186 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_send_log_hb_handler, LINE:183
MESSAGE:leader send sync log msg
VARIABLES:  node->msg_data.set_log_hb_msg.cmd=add 
	 node->msg_data.set_log_hb_msg.key=k1 
	 node->msg_data.set_log_hb_msg.value=1 
	
-----------------------------

09/03/2018 18:57:20.0187	[raft_python_callback.py write_to_logger 66]  187 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:update_DB, LINE:16
MESSAGE:update DB
VARIABLES:  DB_flag=status  key=applied_last_idx 
-----------------------------

09/03/2018 18:57:20.0187	[raft_python_callback.py write_to_logger 66]  187 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:update_DB, LINE:17
MESSAGE:update DB
VARIABLES:  value=0 
-----------------------------

09/03/2018 18:57:20.0189	[raft_python_callback.py write_to_logger 66]  189 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=2 
-----------------------------

09/03/2018 18:57:20.0189	[raft_python_callback.py write_to_logger 66]  189 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_send_log_hb_handler, LINE:197
MESSAGE:leader sending set_log_hb msg
-----------------------------

09/03/2018 18:57:20.0190	[raft_python_callback.py write_to_logger 66]  190 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=180 
-----------------------------

09/03/2018 18:57:20.0190	[raft_python_callback.py write_to_logger 66]  190 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=180 
-----------------------------

09/03/2018 18:57:20.0190	[raft_python_callback.py write_to_logger 66]  190 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=180 
-----------------------------

09/03/2018 18:57:20.0190	[raft_python_callback.py write_to_logger 66]  190 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:20.0190	[raft_python_callback.py write_to_logger 66]  190 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:20.0358	[raft_python_callback.py write_to_logger 66]  358 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:20.0358	[raft_python_callback.py write_to_logger 66]  358 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:is_relevant_message, LINE:168
MESSAGE:check if msg is relevant
VARIABLES:  sharedRaftData.raft_state.current_state=2  node_message->event=3  is_relevant_rv=1  node_message->term=0 
-----------------------------

09/03/2018 18:57:20.0358	[raft_python_callback.py write_to_logger 66]  358 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=1  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:20.0359	[raft_python_callback.py write_to_logger 66]  359 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:20.0359	[raft_python_callback.py write_to_logger 66]  359 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=3  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:20.0359	[raft_python_callback.py write_to_logger 66]  359 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_log_res_handler, LINE:211
MESSAGE:leader log response msg
VARIABLES:  sharedRaftData.raft_state.commit_counter=1 
	 sharedRaftData.raft_state.members_amount=2 
	 sharedRaftData.raft_state.last_commit_index=-1 
	
-----------------------------

09/03/2018 18:57:20.0359	[raft_python_callback.py write_to_logger 66]  359 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=6 
-----------------------------

09/03/2018 18:57:20.0359	[raft_python_callback.py write_to_logger 66]  359 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_log_res_handler, LINE:222
MESSAGE:leader sending commit ok msg
-----------------------------

09/03/2018 18:57:20.0359	[raft_python_callback.py write_to_logger 66]  359 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:20.0359	[raft_python_callback.py write_to_logger 66]  359 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:20.0359	[raft_python_callback.py write_to_logger 66]  359 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:update_DB, LINE:16
MESSAGE:update DB
VARIABLES:  DB_flag=status  key=commit_idx 
-----------------------------

09/03/2018 18:57:20.0360	[raft_python_callback.py write_to_logger 66]  360 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:update_DB, LINE:17
MESSAGE:update DB
VARIABLES:  value=0 
-----------------------------

09/03/2018 18:57:20.0364	[raft_python_callback.py write_to_logger 66]  364 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:20.0365	[raft_python_callback.py write_to_logger 66]  365 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:20.0365	[raft_python_callback.py write_to_logger 66]  365 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:20.0366	[raft_python_callback.py write_to_logger 66]  366 root [CRITI] 
T
09/03/2018 18:57:20.0412	[raft_python_callback.py write_to_logger 66]  412 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:20.0412	[raft_python_callback.py write_to_logger 66]  412 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:20.0412	[raft_python_callback.py write_to_logger 66]  412 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:20.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:20.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:20.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:20.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:20.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:20.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:20.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:20.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:20.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:20.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:20.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:20.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:20.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:20.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:20.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:20.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:20.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:21.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:21.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:21.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:21.0415	[raft_python_callback.py write_to_logger 66]  415 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:21.0415	[raft_python_callback.py write_to_logger 66]  415 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:21.0415	[raft_python_callback.py write_to_logger 66]  415 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:21.0415	[raft_python_callback.py write_to_logger 66]  415 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:21.0415	[raft_python_callback.py write_to_logger 66]  415 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:21.0415	[raft_python_callback.py write_to_logger 66]  415 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:21.0415	[raft_python_callback.py write_to_logger 66]  415 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:21.0912	[raft_python_callback.py write_to_logger 66]  912 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:21.0912	[raft_python_callback.py write_to_logger 66]  912 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:21.0912	[raft_python_callback.py write_to_logger 66]  912 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:21.0912	[raft_python_callback.py write_to_logger 66]  912 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:21.0912	[raft_python_callback.py write_to_logger 66]  912 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:21.0912	[raft_python_callback.py write_to_logger 66]  912 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:21.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:21.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:21.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:21.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:22.0412	[raft_python_callback.py write_to_logger 66]  412 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:22.0412	[raft_python_callback.py write_to_logger 66]  412 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:22.0412	[raft_python_callback.py write_to_logger 66]  412 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:22.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:22.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:22.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:22.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:22.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:22.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:22.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:22.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:22.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:22.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:22.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:22.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:22.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:22.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:22.0915	[raft_python_callback.py write_to_logger 66]  915 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:22.0915	[raft_python_callback.py write_to_logger 66]  915 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:22.0915	[raft_python_callback.py write_to_logger 66]  915 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:23.0412	[raft_python_callback.py write_to_logger 66]  412 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:23.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:23.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:23.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:23.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:23.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:23.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:23.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:23.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:23.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:23.0691	[raft_python_callback.py write_to_logger 66]  691 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:start_commit_process, LINE:173
MESSAGE: start commit process
-----------------------------

09/03/2018 18:57:23.0691	[raft_python_callback.py write_to_logger 66]  691 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=9  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:23.0691	[raft_python_callback.py write_to_logger 66]  691 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_send_log_hb_handler, LINE:180
MESSAGE:leader send new log entry
VARIABLES:  sharedRaftData.raft_state.last_commit_index=0  sharedRaftData.raft_state.last_log_index=0  sharedRaftData.raft_state.commit_counter=2  new_log_commit_id=1 
-----------------------------

09/03/2018 18:57:23.0691	[raft_python_callback.py write_to_logger 66]  691 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_send_log_hb_handler, LINE:183
MESSAGE:leader send sync log msg
VARIABLES:  node->msg_data.set_log_hb_msg.cmd=add 
	 node->msg_data.set_log_hb_msg.key=k2 
	 node->msg_data.set_log_hb_msg.value=1 
	
-----------------------------

09/03/2018 18:57:23.0692	[raft_python_callback.py write_to_logger 66]  692 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:update_DB, LINE:16
MESSAGE:update DB
VARIABLES:  DB_flag=status  key=applied_last_idx 
-----------------------------

09/03/2018 18:57:23.0692	[raft_python_callback.py write_to_logger 66]  692 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:update_DB, LINE:17
MESSAGE:update DB
VARIABLES:  value=1 
-----------------------------

09/03/2018 18:57:23.0693	[raft_python_callback.py write_to_logger 66]  693 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=2 
-----------------------------

09/03/2018 18:57:23.0693	[raft_python_callback.py write_to_logger 66]  693 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_send_log_hb_handler, LINE:197
MESSAGE:leader sending set_log_hb msg
-----------------------------

09/03/2018 18:57:23.0693	[raft_python_callback.py write_to_logger 66]  693 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=180 
-----------------------------

09/03/2018 18:57:23.0693	[raft_python_callback.py write_to_logger 66]  693 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=180 
-----------------------------

09/03/2018 18:57:23.0694	[raft_python_callback.py write_to_logger 66]  694 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=180 
-----------------------------

09/03/2018 18:57:23.0694	[raft_python_callback.py write_to_logger 66]  694 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:23.0694	[raft_python_callback.py write_to_logger 66]  694 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:23.0903	[raft_python_callback.py write_to_logger 66]  903 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:23.0904	[raft_python_callback.py write_to_logger 66]  904 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:is_relevant_message, LINE:168
MESSAGE:check if msg is relevant
VARIABLES:  sharedRaftData.raft_state.current_state=2  node_message->event=3  is_relevant_rv=1  node_message->term=0 
-----------------------------

09/03/2018 18:57:23.0904	[raft_python_callback.py write_to_logger 66]  904 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=1  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:23.0904	[raft_python_callback.py write_to_logger 66]  904 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=3  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:23.0904	[raft_python_callback.py write_to_logger 66]  904 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_log_res_handler, LINE:211
MESSAGE:leader log response msg
VARIABLES:  sharedRaftData.raft_state.commit_counter=3 
	 sharedRaftData.raft_state.members_amount=2 
	 sharedRaftData.raft_state.last_commit_index=0 
	
-----------------------------

09/03/2018 18:57:23.0904	[raft_python_callback.py write_to_logger 66]  904 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:23.0905	[raft_python_callback.py write_to_logger 66]  905 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=6 
-----------------------------

09/03/2018 18:57:23.0905	[raft_python_callback.py write_to_logger 66]  905 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_log_res_handler, LINE:222
MESSAGE:leader sending commit ok msg
-----------------------------

09/03/2018 18:57:23.0905	[raft_python_callback.py write_to_logger 66]  905 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:23.0905	[raft_python_callback.py write_to_logger 66]  905 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:23.0905	[raft_python_callback.py write_to_logger 66]  905 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:update_DB, LINE:16
MESSAGE:update DB
VARIABLES:  DB_flag=status  key=commit_idx 
-----------------------------

09/03/2018 18:57:23.0906	[raft_python_callback.py write_to_logger 66]  906 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:update_DB, LINE:17
MESSAGE:update DB
VARIABLES:  value=1 
-----------------------------

09/03/2018 18:57:23.0906	[raft_python_callback.py write_to_logger 66]  906 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:23.0906	[raft_python_callback.py write_to_logger 66]  906 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:23.0906	[raft_python_callback.py write_to_logger 66]  906 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:23.0908	[raft_python_callback.py write_to_logger 66]  908 root [CRITI] 
T
09/03/2018 18:57:23.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:23.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:23.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:23.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:23.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:23.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:23.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:23.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:23.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:23.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:24.0412	[raft_python_callback.py write_to_logger 66]  412 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:24.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:24.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:24.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:24.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:24.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:24.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:24.0457	[raft_python_callback.py write_to_logger 66]  457 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:24.0458	[raft_python_callback.py write_to_logger 66]  458 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:24.0458	[raft_python_callback.py write_to_logger 66]  458 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:24.0912	[raft_python_callback.py write_to_logger 66]  912 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:24.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:24.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:24.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:24.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:24.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:24.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:24.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:24.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:24.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:25.0412	[raft_python_callback.py write_to_logger 66]  412 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:25.0412	[raft_python_callback.py write_to_logger 66]  412 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:25.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:25.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:25.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:25.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:25.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:25.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:25.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:25.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:25.0912	[raft_python_callback.py write_to_logger 66]  912 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:25.0912	[raft_python_callback.py write_to_logger 66]  912 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:25.0912	[raft_python_callback.py write_to_logger 66]  912 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:25.0912	[raft_python_callback.py write_to_logger 66]  912 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:25.0912	[raft_python_callback.py write_to_logger 66]  912 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:25.0912	[raft_python_callback.py write_to_logger 66]  912 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:25.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:25.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:25.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:25.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:26.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:26.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:26.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:26.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:26.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:26.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:26.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:26.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:26.0415	[raft_python_callback.py write_to_logger 66]  415 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:26.0415	[raft_python_callback.py write_to_logger 66]  415 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:26.0560	[raft_python_callback.py write_to_logger 66]  560 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:start_commit_process, LINE:173
MESSAGE: start commit process
-----------------------------

09/03/2018 18:57:26.0561	[raft_python_callback.py write_to_logger 66]  561 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=9  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:26.0561	[raft_python_callback.py write_to_logger 66]  561 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_send_log_hb_handler, LINE:180
MESSAGE:leader send new log entry
VARIABLES:  sharedRaftData.raft_state.last_commit_index=1  sharedRaftData.raft_state.last_log_index=1  sharedRaftData.raft_state.commit_counter=4  new_log_commit_id=2 
-----------------------------

09/03/2018 18:57:26.0561	[raft_python_callback.py write_to_logger 66]  561 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_send_log_hb_handler, LINE:183
MESSAGE:leader send sync log msg
VARIABLES:  node->msg_data.set_log_hb_msg.cmd=add 
	 node->msg_data.set_log_hb_msg.key=k3 
	 node->msg_data.set_log_hb_msg.value=1 
	
-----------------------------

09/03/2018 18:57:26.0563	[raft_python_callback.py write_to_logger 66]  563 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:update_DB, LINE:16
MESSAGE:update DB
VARIABLES:  DB_flag=status  key=applied_last_idx 
-----------------------------

09/03/2018 18:57:26.0563	[raft_python_callback.py write_to_logger 66]  563 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:update_DB, LINE:17
MESSAGE:update DB
VARIABLES:  value=2 
-----------------------------

09/03/2018 18:57:26.0564	[raft_python_callback.py write_to_logger 66]  564 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=2 
-----------------------------

09/03/2018 18:57:26.0564	[raft_python_callback.py write_to_logger 66]  564 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_send_log_hb_handler, LINE:197
MESSAGE:leader sending set_log_hb msg
-----------------------------

09/03/2018 18:57:26.0564	[raft_python_callback.py write_to_logger 66]  564 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=180 
-----------------------------

09/03/2018 18:57:26.0565	[raft_python_callback.py write_to_logger 66]  565 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=180 
-----------------------------

09/03/2018 18:57:26.0565	[raft_python_callback.py write_to_logger 66]  565 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=180 
-----------------------------

09/03/2018 18:57:26.0565	[raft_python_callback.py write_to_logger 66]  565 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:26.0565	[raft_python_callback.py write_to_logger 66]  565 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:26.0770	[raft_python_callback.py write_to_logger 66]  770 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:26.0770	[raft_python_callback.py write_to_logger 66]  770 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:is_relevant_message, LINE:168
MESSAGE:check if msg is relevant
VARIABLES:  sharedRaftData.raft_state.current_state=2  node_message->event=3  is_relevant_rv=1  node_message->term=0 
-----------------------------

09/03/2018 18:57:26.0771	[raft_python_callback.py write_to_logger 66]  771 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=1  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:26.0771	[raft_python_callback.py write_to_logger 66]  771 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:26.0771	[raft_python_callback.py write_to_logger 66]  771 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=3  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:26.0771	[raft_python_callback.py write_to_logger 66]  771 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_log_res_handler, LINE:211
MESSAGE:leader log response msg
VARIABLES:  sharedRaftData.raft_state.commit_counter=5 
	 sharedRaftData.raft_state.members_amount=2 
	 sharedRaftData.raft_state.last_commit_index=1 
	
-----------------------------

09/03/2018 18:57:26.0771	[raft_python_callback.py write_to_logger 66]  771 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=6 
-----------------------------

09/03/2018 18:57:26.0771	[raft_python_callback.py write_to_logger 66]  771 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_log_res_handler, LINE:222
MESSAGE:leader sending commit ok msg
-----------------------------

09/03/2018 18:57:26.0771	[raft_python_callback.py write_to_logger 66]  771 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:26.0772	[raft_python_callback.py write_to_logger 66]  772 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:26.0772	[raft_python_callback.py write_to_logger 66]  772 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:update_DB, LINE:16
MESSAGE:update DB
VARIABLES:  DB_flag=status  key=commit_idx 
-----------------------------

09/03/2018 18:57:26.0772	[raft_python_callback.py write_to_logger 66]  772 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:update_DB, LINE:17
MESSAGE:update DB
VARIABLES:  value=2 
-----------------------------

09/03/2018 18:57:26.0772	[raft_python_callback.py write_to_logger 66]  772 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:26.0772	[raft_python_callback.py write_to_logger 66]  772 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:26.0773	[raft_python_callback.py write_to_logger 66]  773 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:26.0774	[raft_python_callback.py write_to_logger 66]  774 root [CRITI] 
T
09/03/2018 18:57:26.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:26.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:26.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:26.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:26.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:26.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:26.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:26.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:26.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:26.0915	[raft_python_callback.py write_to_logger 66]  915 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:27.0412	[raft_python_callback.py write_to_logger 66]  412 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:27.0412	[raft_python_callback.py write_to_logger 66]  412 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:27.0412	[raft_python_callback.py write_to_logger 66]  412 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:27.0412	[raft_python_callback.py write_to_logger 66]  412 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:27.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:27.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:27.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:27.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:27.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:27.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:27.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:27.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:27.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:27.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:27.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:27.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:27.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:27.0914	[raft_python_callback.py write_to_logger 66]  914 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:27.0915	[raft_python_callback.py write_to_logger 66]  915 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:27.0915	[raft_python_callback.py write_to_logger 66]  915 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:28.0412	[raft_python_callback.py write_to_logger 66]  412 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:28.0412	[raft_python_callback.py write_to_logger 66]  412 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:28.0412	[raft_python_callback.py write_to_logger 66]  412 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:28.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:28.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:28.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:28.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:28.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:28.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:28.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:28.0708	[raft_python_callback.py write_to_logger 66]  708 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:start_commit_process, LINE:173
MESSAGE: start commit process
-----------------------------

09/03/2018 18:57:28.0708	[raft_python_callback.py write_to_logger 66]  708 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=9  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:28.0708	[raft_python_callback.py write_to_logger 66]  708 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_send_log_hb_handler, LINE:180
MESSAGE:leader send new log entry
VARIABLES:  sharedRaftData.raft_state.last_commit_index=2  sharedRaftData.raft_state.last_log_index=2  sharedRaftData.raft_state.commit_counter=6  new_log_commit_id=3 
-----------------------------

09/03/2018 18:57:28.0708	[raft_python_callback.py write_to_logger 66]  708 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_send_log_hb_handler, LINE:183
MESSAGE:leader send sync log msg
VARIABLES:  node->msg_data.set_log_hb_msg.cmd=add 
	 node->msg_data.set_log_hb_msg.key=k4 
	 node->msg_data.set_log_hb_msg.value=1 
	
-----------------------------

09/03/2018 18:57:28.0709	[raft_python_callback.py write_to_logger 66]  709 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:update_DB, LINE:16
MESSAGE:update DB
VARIABLES:  DB_flag=status  key=applied_last_idx 
-----------------------------

09/03/2018 18:57:28.0709	[raft_python_callback.py write_to_logger 66]  709 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:update_DB, LINE:17
MESSAGE:update DB
VARIABLES:  value=3 
-----------------------------

09/03/2018 18:57:28.0711	[raft_python_callback.py write_to_logger 66]  711 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=2 
-----------------------------

09/03/2018 18:57:28.0711	[raft_python_callback.py write_to_logger 66]  711 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_send_log_hb_handler, LINE:197
MESSAGE:leader sending set_log_hb msg
-----------------------------

09/03/2018 18:57:28.0711	[raft_python_callback.py write_to_logger 66]  711 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=180 
-----------------------------

09/03/2018 18:57:28.0711	[raft_python_callback.py write_to_logger 66]  711 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=180 
-----------------------------

09/03/2018 18:57:28.0711	[raft_python_callback.py write_to_logger 66]  711 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=180 
-----------------------------

09/03/2018 18:57:28.0711	[raft_python_callback.py write_to_logger 66]  711 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:28.0711	[raft_python_callback.py write_to_logger 66]  711 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:28.0912	[raft_python_callback.py write_to_logger 66]  912 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:28.0912	[raft_python_callback.py write_to_logger 66]  912 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:28.0912	[raft_python_callback.py write_to_logger 66]  912 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:28.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:28.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:28.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:28.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:28.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:28.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:28.0913	[raft_python_callback.py write_to_logger 66]  913 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:29.0412	[raft_python_callback.py write_to_logger 66]  412 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:time_out_hendler, LINE:77
MESSAGE:add new timeout event- now in queue
VARIABLES:  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:29.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=0  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:29.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:122
MESSAGE:leader timeout event
-----------------------------

09/03/2018 18:57:29.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/static_queue.c, FUNCTION:create_new_queue_node_data, LINE:107
MESSAGE:create new msg
VARIABLES:  event=1 
-----------------------------

09/03/2018 18:57:29.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_time_out_handler, LINE:126
MESSAGE:leader sending keep alive hb msg
-----------------------------

09/03/2018 18:57:29.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:100
MESSAGE:try to send msg
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:29.0413	[raft_python_callback.py write_to_logger 66]  413 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:send_raft_message, LINE:118
MESSAGE:msg was successfully sent
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:29.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=24 
-----------------------------

09/03/2018 18:57:29.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=2  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:29.0414	[raft_python_callback.py write_to_logger 66]  414 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:29.0536	[raft_python_callback.py write_to_logger 66]  536 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:155
MESSAGE:msg was successfully read
VARIABLES:  message_size=28 
-----------------------------

09/03/2018 18:57:29.0536	[raft_python_callback.py write_to_logger 66]  536 root [DEBUG] 
FILE:./C/Code/handlers_utils.c, FUNCTION:is_relevant_message, LINE:168
MESSAGE:check if msg is relevant
VARIABLES:  sharedRaftData.raft_state.current_state=2  node_message->event=4  is_relevant_rv=1  node_message->term=0 
-----------------------------

09/03/2018 18:57:29.0536	[raft_python_callback.py write_to_logger 66]  536 root [DEBUG] 
FILE:./raft_main.c, FUNCTION:run_multicast_listener, LINE:21
MESSAGE:got new message and ids as followed:
VARIABLES:  new_node.message_sent_by=1  sharedRaftData.raft_state.server_id=2 
-----------------------------

09/03/2018 18:57:29.0537	[raft_python_callback.py write_to_logger 66]  537 root [DEBUG] 
FILE:./C/Code/raft_server.c, FUNCTION:get_raft_message, LINE:131
MESSAGE:try to read message
-----------------------------

09/03/2018 18:57:29.0537	[raft_python_callback.py write_to_logger 66]  537 root [DEBUG] 
FILE:./C/Code/state_machine.c, FUNCTION:operate_machine_state, LINE:8
MESSAGE:enter state function
VARIABLES:  node->event=4  sharedRaftData.raft_state.current_state=2 
-----------------------------

09/03/2018 18:57:29.0537	[raft_python_callback.py write_to_logger 66]  537 root [DEBUG] 
FILE:./C/Code/leader_handlers.c, FUNCTION:leader_sync_req_handler, LINE:12
MESSAGE:leader get sync request msg
VARIABLES:  sharedRaftData.raft_state.last_commit_index=2  sharedRaftData.raft_state.last_log_index=3  node->msg_data.sync_req_msg.start_log_index=3  node->msg_data.sync_req_msg.last_log_id=3  node->message_sent_by=1 
-----------------------------

